### ISSUE TITLE
Create readme.md

### ISSUE THREAD

**Issue by Neeraj319** [Neeraj319/django-blog-app-#2]

**Comment by Knackie** [comment]
Can i work on this ?

**Comment by Neeraj319** [comment]
yes surely why not

**Comment by Knackie** [comment]
could you explain me your project ? :)

**Comment by Neeraj319** [comment]
its a blog app where users can login create their blog post it they can read the blog comment on it like the comment oh and the most liked comment stays on the top users also can login through facebook admin can update their profile picture if user dosent have one then a deafult will be added from static files

**Comment by Knackie** [comment]
ok, did you have an example somewhere of this ?

**Comment by Neeraj319** [comment]
why dont you cone the repo and try it on your pc you will understand better

**Comment by Knackie** [comment]
i just ask if you have any example of running instance.

**Comment by Neeraj319** [comment]
i dont understand can you be more specific?

**Comment by Knackie** [comment]
I ask to know if i can see a running instance of this project online

**Comment by Neeraj319** [comment]
you wanna host it online?

**Comment by Yashi30** [comment]
I want to work on this!!

**Comment by Neeraj319** [comment]
Yes you can work on it this is open source

**Comment by Neeraj319** [comment]
> Yes you can work on it this is open source

Important

**Comment by Yashi30** [comment]
Please add hactoberfest-accepted label in this PR  , so that it will count in my PR's ; Hoping for a positive response

**Comment by Neeraj319** [comment]
i think i have labeled it now please check and infrom me
